### ISSUE TITLE
is the init_ffa() correct?

### ISSUE THREAD

**Issue by icehuli** [firefly-cpp/Firefly-algorithm--FFA-#1]
in the init_ffa() function:
    for (i = 0;i<n;i++){
        for (j = 0;j<D;j++){
            r = ((double)rand() / ((double)(RAND_MAX)+(double)(1)));
            ffa[i][j] = r*(ub[i] - lb[i]) + lb[i];

ub[i] and lb[i] should be changed to ub[j] and lb[j].

**Comment by firefly-cpp** [comment]
Correct. Thank you.
