### ISSUE TITLE
Maximum array size declaration correction

### ISSUE THREAD

**Issue by NashSam** [firefly-cpp/Firefly-algorithm--FFA-#2]
`double nbest[**MAX_FFA**];          // the best solution found so far`

Should be :

`double nbest[**MAX_D**];          // the best solution found so far`

> The solution is the multi-dimensional coordinates of the fittest firefly. In the case where 
> (D<MAX_D)>MAX_FFA could cause an out of bounds error.

**Comment by firefly-cpp** [comment]
Corrected!

Thank you @NashSam
